import { Category } from "../types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat_mobile",
    name: "Mobile Repair",
    slug: "mobile-repair",
    description: "Doorstep screen replacement, battery, charging port, and hardware repair within 60 mins.",
    imageUrl: "phone",
    isActive: true,
    subcategories: [
      {
        id: "sub_mob_doorstep",
        categoryId: "cat_mobile",
        name: "Doorstep Mobile Screen & Hardware Repair",
        slug: "doorstep-mobile-repair",
        description: "Certified technicians fix your phone right in front of you at your home or office.",
        basePrice: 499,
        imageUrl: "smartphone",
        formConfig: {
          fields: [
            {
              id: "device_model",
              label: "Mobile Brand & Model",
              type: "TEXT",
              placeholder: "e.g., iPhone 13, OnePlus 11, Samsung S23, Redmi Note 12",
              validation: { required: true, min: 2 },
            },
            {
              id: "repair_type",
              label: "Required Repair Service",
              type: "SELECT",
              options: [
                { label: "Original Screen Replacement", value: "screen", priceModifier: 1499 },
                { label: "Battery Replacement (100% Health)", value: "battery", priceModifier: 799 },
                { label: "Charging Port / Mic Replacement", value: "charging", priceModifier: 399 },
                { label: "Back Glass / Camera Glass Fix", value: "camera_glass", priceModifier: 499 },
                { label: "Water Damage / Motherboard Diagnosis", value: "motherboard", priceModifier: 599 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Preferred Visit Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Preferred Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Doorstep Service Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_ac_repair",
    name: "AC Repair & Service",
    slug: "ac-repair",
    description: "Deep jet foam cleaning, gas refill, installation, cooling issues & PCB breakdown repairs.",
    imageUrl: "wind",
    isActive: true,
    subcategories: [
      {
        id: "sub_ac_service",
        categoryId: "cat_ac_repair",
        name: "Split & Window AC Complete Service",
        slug: "split-window-ac-service",
        description: "Power jet deep cleaning with foam spray, coil check & cooling optimization.",
        basePrice: 399,
        imageUrl: "wind",
        formConfig: {
          fields: [
            {
              id: "ac_type",
              label: "AC Type & Ton",
              type: "SELECT",
              options: [
                { label: "Split AC (1 - 1.5 Ton)", value: "split_1.5", priceModifier: 100 },
                { label: "Split AC (2 Ton)", value: "split_2", priceModifier: 200 },
                { label: "Window AC (All Sizes)", value: "window", priceModifier: 0 },
                { label: "Cassette / Tower Commercial AC", value: "cassette", priceModifier: 600 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "service_required",
              label: "Service Needed",
              type: "SELECT",
              options: [
                { label: "Power Jet Deep Cleaning & Foam Wash", value: "jet_service", priceModifier: 250 },
                { label: "Gas Leakage Detection & Full Gas Refill", value: "gas_refill", priceModifier: 1400 },
                { label: "AC Not Cooling / Water Dripping Issue", value: "not_cooling", priceModifier: 199 },
                { label: "New AC Installation / Uninstallation", value: "installation", priceModifier: 800 },
                { label: "PCB / Inverter Motherboard Repair", value: "pcb_repair", priceModifier: 950 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Service Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Service Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_electrician",
    name: "Electrician",
    slug: "electrician",
    description: "Certified electricians for fan, switchboard, MCB wiring, lights & short-circuit breakdown.",
    imageUrl: "zap",
    isActive: true,
    subcategories: [
      {
        id: "sub_electrician_general",
        categoryId: "cat_electrician",
        name: "Electrician Doorstep Visit & Repair",
        slug: "electrician-visit",
        description: "Instant doorstep assistance for domestic & commercial electrical faults.",
        basePrice: 199,
        imageUrl: "zap",
        formConfig: {
          fields: [
            {
              id: "electrical_job",
              label: "Choose Electrical Work",
              type: "SELECT",
              options: [
                { label: "Fan Repair / Installation / Regulators", value: "fan", priceModifier: 150 },
                { label: "Switchboard / Socket / Fuse Replacement", value: "switchboard", priceModifier: 100 },
                { label: "MCB Tripping / Short Circuit Fault Finding", value: "mcb_fault", priceModifier: 350 },
                { label: "Inverter & Battery Wiring Setup", value: "inverter", priceModifier: 400 },
                { label: "Decorative Chandelier & LED Strip Lighting", value: "led_lights", priceModifier: 300 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Preferred Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Preferred Time",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Home Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_plumber",
    name: "Plumber",
    slug: "plumber",
    description: "Expert plumbers for tap repair, pipe leakages, water tank cleaning, shower & toilet fittings.",
    imageUrl: "droplets",
    isActive: true,
    subcategories: [
      {
        id: "sub_plumber_visit",
        categoryId: "cat_plumber",
        name: "Plumbing Inspection & Repair",
        slug: "plumbing-repair",
        description: "Quick doorstep solution for blocked drains, tap leaks & sanitary installations.",
        basePrice: 199,
        imageUrl: "droplets",
        formConfig: {
          fields: [
            {
              id: "plumbing_issue",
              label: "Select Plumbing Requirement",
              type: "SELECT",
              options: [
                { label: "Tap / Mixer / Shower Leakage Repair", value: "tap_leak", priceModifier: 100 },
                { label: "Drain Blockage / Clogged Basin Cleaning", value: "blockage", priceModifier: 250 },
                { label: "Water Tank Deep Cleaning (500L - 1000L)", value: "tank_clean", priceModifier: 600 },
                { label: "Toilet Seat / Flush Tank Replacement", value: "toilet_fit", priceModifier: 450 },
                { label: "Main Water Motor / Pump Pipe Fitting", value: "motor_pipe", priceModifier: 350 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_carpenter",
    name: "Carpenter",
    slug: "carpenter",
    description: "Furniture repair, bed assembly, modular kitchen fittings, door locks, hinges & wood polish.",
    imageUrl: "hammer",
    isActive: true,
    subcategories: [
      {
        id: "sub_carpenter_visit",
        categoryId: "cat_carpenter",
        name: "Carpentry & Furniture Works",
        slug: "carpentry-works",
        description: "Skilled carpenters for quick repairs, new fittings and custom woodwork.",
        basePrice: 299,
        imageUrl: "hammer",
        formConfig: {
          fields: [
            {
              id: "carpenter_work",
              label: "Carpentry Requirement",
              type: "SELECT",
              options: [
                { label: "Door Lock / Latch / Handle Fitting", value: "lock_fitting", priceModifier: 150 },
                { label: "Bed / Wardrobe Assembly & Disassembly", value: "bed_assembly", priceModifier: 500 },
                { label: "Cabinet / Drawer Hinge & Channel Repair", value: "hinge_fix", priceModifier: 200 },
                { label: "Wooden Partition / Shelves Installation", value: "shelves", priceModifier: 400 },
                { label: "Wood Polishing & Touch-up (Small / Large)", value: "polishing", priceModifier: 650 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_cleaning",
    name: "Home Cleaning",
    slug: "home-cleaning",
    description: "Full home deep cleaning, kitchen & bathroom sanitation, sofa, carpet & mattress shampoo.",
    imageUrl: "sparkles",
    isActive: true,
    subcategories: [
      {
        id: "sub_home_deep_clean",
        categoryId: "cat_cleaning",
        name: "Deep Home Cleaning & Sanitation",
        slug: "deep-home-cleaning",
        description: "Eco-friendly chemicals, motorized floor scrubbers and trained cleaners.",
        basePrice: 599,
        imageUrl: "sparkles",
        formConfig: {
          fields: [
            {
              id: "cleaning_package",
              label: "Choose Cleaning Package",
              type: "SELECT",
              options: [
                { label: "Bathroom Deep Cleaning (Per Bathroom)", value: "bathroom", priceModifier: 299 },
                { label: "Kitchen Deep Degreasing & Cabinet Clean", value: "kitchen", priceModifier: 699 },
                { label: "1 BHK Full Home Deep Cleaning", value: "1bhk", priceModifier: 1499 },
                { label: "2 BHK Full Home Deep Cleaning", value: "2bhk", priceModifier: 2199 },
                { label: "3 BHK Full Home Deep Cleaning", value: "3bhk", priceModifier: 2899 },
                { label: "Sofa / Carpet Dry Cleaning & Shampoo", value: "sofa_clean", priceModifier: 550 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_salon",
    name: "Home Salon",
    slug: "home-salon",
    description: "Hygienic salon at home for women & men: facials, waxing, manicure, pedicure & hair styling.",
    imageUrl: "scissors",
    isActive: true,
    subcategories: [
      {
        id: "sub_salon_package",
        categoryId: "cat_salon",
        name: "Beauty, Hair & Spa Treatments",
        slug: "beauty-spa-home",
        description: "100% single-use disposable kits and branded premium beauty products.",
        basePrice: 499,
        imageUrl: "scissors",
        formConfig: {
          fields: [
            {
              id: "salon_package",
              label: "Select Salon Services",
              type: "MULTI_SELECT",
              options: [
                { label: "Diamond Glowing Facial & Clean-up", value: "facial", priceModifier: 699 },
                { label: "Honey Full Arms & Legs Waxing", value: "waxing", priceModifier: 499 },
                { label: "Rose Petal Deluxe Pedicure & Manicure", value: "pedi_mani", priceModifier: 599 },
                { label: "Hair Spa + Head Massage + Blow Dry", value: "hair_spa", priceModifier: 799 },
                { label: "Men Haircut & Beard Styling + De-tan", value: "men_grooming", priceModifier: 399 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_appliance",
    name: "Appliance Repair",
    slug: "appliance-repair",
    description: "Doorstep service for Microwave Oven, Geyser, Water Heater, Mixer & Kitchen Chimney.",
    imageUrl: "wrench",
    isActive: true,
    subcategories: [
      {
        id: "sub_small_appliance",
        categoryId: "cat_appliance",
        name: "Small & Kitchen Appliance Repair",
        slug: "small-appliance-repair",
        description: "Fast doorstep troubleshooting for all electrical appliances with genuine spares.",
        basePrice: 299,
        imageUrl: "wrench",
        formConfig: {
          fields: [
            {
              id: "appliance_type",
              label: "Appliance to Repair",
              type: "SELECT",
              options: [
                { label: "Geyser / Water Heater Not Heating / Leaking", value: "geyser", priceModifier: 150 },
                { label: "Microwave Oven / OTG Not Heating / Sparking", value: "microwave", priceModifier: 200 },
                { label: "Kitchen Chimney Deep Cleaning & Motor Fix", value: "chimney", priceModifier: 450 },
                { label: "Mixer / Grinder / Juicer Blade & Motor", value: "mixer", priceModifier: 100 },
                { label: "Induction Cooktop / Electric Kettle", value: "induction", priceModifier: 150 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_painting",
    name: "Painting",
    slug: "painting",
    description: "Interior & exterior wall painting, waterproof damp treatment, texture paint and stencil designs.",
    imageUrl: "paint-brush",
    isActive: true,
    subcategories: [
      {
        id: "sub_painting_services",
        categoryId: "cat_painting",
        name: "House & Wall Painting Services",
        slug: "home-painting",
        description: "Laser measurement, wall putty, primer & premium Asian/Berger paint coating.",
        basePrice: 999,
        imageUrl: "paint-brush",
        formConfig: {
          fields: [
            {
              id: "painting_scope",
              label: "Painting Scope",
              type: "SELECT",
              options: [
                { label: "Single Room / Accent Wall Makeover", value: "single_room", priceModifier: 800 },
                { label: "Complete 1/2/3 BHK Interior Painting", value: "full_interior", priceModifier: 3500 },
                { label: "Waterproofing & Damp Wall Treatment", value: "waterproofing", priceModifier: 1200 },
                { label: "Wall Texture & Designer Stencils", value: "texture", priceModifier: 950 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Inspection Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_cctv",
    name: "CCTV Installation",
    slug: "cctv-installation",
    description: "IP & HD CCTV security camera installation, DVR/NVR setup, mobile view and cable routing.",
    imageUrl: "camera",
    isActive: true,
    subcategories: [
      {
        id: "sub_cctv_setup",
        categoryId: "cat_cctv",
        name: "CCTV Security Camera Setup",
        slug: "cctv-setup",
        description: "Professional camera alignment, smartphone live remote viewing and night vision config.",
        basePrice: 499,
        imageUrl: "camera",
        formConfig: {
          fields: [
            {
              id: "cctv_service",
              label: "CCTV Requirement",
              type: "SELECT",
              options: [
                { label: "New CCTV Camera Installation (Per Camera)", value: "new_install", priceModifier: 250 },
                { label: "Complete 4-Camera Setup with DVR & Hard Disk", value: "4_cam_kit", priceModifier: 1200 },
                { label: "CCTV Mobile App Remote View / Offline Fix", value: "mobile_view", priceModifier: 200 },
                { label: "Camera Relocation / Wire Routing & Repair", value: "relocate", priceModifier: 350 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_ro_service",
    name: "RO Service",
    slug: "ro-service",
    description: "Water purifier RO filter change, membrane replacement, UV lamp fix and TDS calibration.",
    imageUrl: "droplet",
    isActive: true,
    subcategories: [
      {
        id: "sub_ro_filter_change",
        categoryId: "cat_ro_service",
        name: "RO Purifier Maintenance & Repair",
        slug: "ro-purifier-repair",
        description: "Genuine Kent, Aquaguard, Livpure filters with strict water TDS testing.",
        basePrice: 299,
        imageUrl: "droplet",
        formConfig: {
          fields: [
            {
              id: "ro_service_type",
              label: "Select RO Service",
              type: "SELECT",
              options: [
                { label: "General Service & Complete Filter Deep Clean", value: "general_clean", priceModifier: 150 },
                { label: "Sediment + Carbon + Post Carbon Filter Set", value: "filter_set", priceModifier: 650 },
                { label: "RO Membrane Replacement (High TDS Fix)", value: "membrane", priceModifier: 1100 },
                { label: "Water Purifier Booster Pump / SMPS Repair", value: "pump_smps", priceModifier: 750 },
                { label: "New RO Purifier Installation / Uninstallation", value: "ro_install", priceModifier: 350 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_computer",
    name: "Computer/Laptop Repair",
    slug: "computer-laptop-repair",
    description: "Doorstep diagnostic for slow laptops, Windows/Mac OS install, SSD speedup, keyboard & screen.",
    imageUrl: "monitor",
    isActive: true,
    subcategories: [
      {
        id: "sub_computer_repair",
        categoryId: "cat_computer",
        name: "Laptop & PC Doorstep Diagnostic",
        slug: "laptop-pc-repair",
        description: "Hardware & software fixes for Dell, HP, Lenovo, Asus, Acer & Apple MacBook.",
        basePrice: 499,
        imageUrl: "monitor",
        formConfig: {
          fields: [
            {
              id: "laptop_issue",
              label: "Issue / Required Upgrade",
              type: "SELECT",
              options: [
                { label: "High-Speed SSD Upgrade (Make Laptop 10x Faster)", value: "ssd_speedup", priceModifier: 350 },
                { label: "Original Windows 11 / Mac OS Installation", value: "os_install", priceModifier: 300 },
                { label: "Laptop Screen / Display Replacement", value: "screen_replace", priceModifier: 1800 },
                { label: "Laptop Battery / Charger / Power Jack Repair", value: "battery_power", priceModifier: 450 },
                { label: "Motherboard Chip-Level Repair / Dead Laptop", value: "motherboard", priceModifier: 950 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_washing_machine",
    name: "Washing Machine Repair",
    slug: "washing-machine-repair",
    description: "Front load & top load washing machine repair: water leakage, drum noise, vibration & PCB.",
    imageUrl: "disc",
    isActive: true,
    subcategories: [
      {
        id: "sub_washing_machine_fix",
        categoryId: "cat_washing_machine",
        name: "Automatic & Semi-Automatic Machine Repair",
        slug: "washing-machine-repair-service",
        description: "Certified technicians for LG, Samsung, Whirlpool, IFB, Bosch & Haier.",
        basePrice: 349,
        imageUrl: "disc",
        formConfig: {
          fields: [
            {
              id: "machine_type",
              label: "Machine Type",
              type: "SELECT",
              options: [
                { label: "Fully Automatic Front Load", value: "front_load", priceModifier: 150 },
                { label: "Fully Automatic Top Load", value: "top_load", priceModifier: 100 },
                { label: "Semi-Automatic (Twin Tub)", value: "semi_auto", priceModifier: 0 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "machine_problem",
              label: "Primary Problem",
              type: "SELECT",
              options: [
                { label: "Machine Not Spinning / Drum Not Moving", value: "not_spinning", priceModifier: 200 },
                { label: "Water Not Draining / Continuous Water Intake", value: "water_issue", priceModifier: 150 },
                { label: "Excessive Vibration & Noise during Spin", value: "noise_vibration", priceModifier: 300 },
                { label: "Machine Dead / PCB Display Error Codes", value: "pcb_error", priceModifier: 600 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_refrigerator",
    name: "Refrigerator Repair",
    slug: "refrigerator-repair",
    description: "Doorstep fridge repair: single & double door, cooling fault, compressor, gas charge & thermostat.",
    imageUrl: "snowflake",
    isActive: true,
    subcategories: [
      {
        id: "sub_fridge_repair",
        categoryId: "cat_refrigerator",
        name: "Refrigerator Cooling & Gas Service",
        slug: "fridge-service",
        description: "Same-day doorstep inspection for Samsung, LG, Whirlpool, Godrej & Haier.",
        basePrice: 349,
        imageUrl: "snowflake",
        formConfig: {
          fields: [
            {
              id: "fridge_type",
              label: "Refrigerator Type",
              type: "SELECT",
              options: [
                { label: "Single Door Refrigerator", value: "single_door", priceModifier: 0 },
                { label: "Double Door Frost-Free Refrigerator", value: "double_door", priceModifier: 150 },
                { label: "Side-by-Side / French Door Fridge", value: "side_by_side", priceModifier: 400 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "fridge_issue",
              label: "Issue Observed",
              type: "SELECT",
              options: [
                { label: "Fridge Not Cooling / Low Cooling", value: "not_cooling", priceModifier: 200 },
                { label: "Compressor Gas Charging & Leakage Repair", value: "gas_charge", priceModifier: 1250 },
                { label: "Water Leakage Inside / Ice Sheet Formation", value: "leakage_ice", priceModifier: 250 },
                { label: "Thermostat / Relay / Fan Motor Replacement", value: "thermostat", priceModifier: 450 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_pest_control",
    name: "Pest Control",
    slug: "pest-control",
    description: "Safe & herbal pest control for cockroaches, termites, bed bugs, ants and mosquitoes.",
    imageUrl: "bug",
    isActive: true,
    subcategories: [
      {
        id: "sub_pest_control_service",
        categoryId: "cat_pest_control",
        name: "Herbal & Odorless Pest Control",
        slug: "home-pest-control",
        description: "100% kid & pet-safe odorless gel and spray with warranty guarantee.",
        basePrice: 699,
        imageUrl: "bug",
        formConfig: {
          fields: [
            {
              id: "pest_type",
              label: "Pest Treatment Type",
              type: "SELECT",
              options: [
                { label: "Cockroach & Ant Herbal Gel (1-3 BHK)", value: "cockroach", priceModifier: 300 },
                { label: "Bed Bugs Complete 2-Visit Treatment", value: "bed_bugs", priceModifier: 900 },
                { label: "Termite (Deemak) Wood & Wall Drilling", value: "termite", priceModifier: 1500 },
                { label: "Mosquito & Flying Insect Fogging", value: "mosquito", priceModifier: 500 },
                { label: "Complete Home 360° All-Pest Protection", value: "all_pest", priceModifier: 1200 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
];

export const MOCK_BRANDS: import("../types").MobileBrand[] = [
  {
    id: "brand_apple",
    name: "Apple",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/500px-Apple_logo_black.svg.png",
    models: ["iPhone 16 Pro Max", "iPhone 16", "iPhone 15 Pro", "iPhone 15", "iPhone 14", "iPhone 13", "iPhone 12", "iPhone 11"],
    repairs: [
      { name: "Original Retina OLED Screen", price: 3499 },
      { name: "Original Battery (100% Health)", price: 1899 },
      { name: "Back Glass & Housing Replacement", price: 1299 },
      { name: "Camera Lens & FaceID Repair", price: 1499 },
    ],
  },
  {
    id: "brand_samsung",
    name: "Samsung",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/500px-Samsung_Logo.svg.png",
    models: ["Galaxy S24 Ultra", "Galaxy S23", "Galaxy Z Fold 5", "Galaxy A55", "Galaxy M34 5G", "Galaxy F54"],
    repairs: [
      { name: "Dynamic AMOLED 2X Display", price: 2999 },
      { name: "Super Fast Charging Port Fix", price: 499 },
      { name: "6000mAh Battery Replacement", price: 999 },
      { name: "Motherboard & IC Repair", price: 1199 },
    ],
  },
  {
    id: "brand_xiaomi",
    name: "Xiaomi / Redmi",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Xiaomi_logo_%282021-%29.svg/500px-Xiaomi_logo_%282021-%29.svg.png",
    models: ["Redmi Note 13 Pro+", "Redmi Note 12 5G", "Redmi 13C", "Xiaomi 14", "Xiaomi 13 Pro"],
    repairs: [
      { name: "120Hz AMOLED Screen Glass", price: 1499 },
      { name: "Battery & 67W Turbo Charge Board", price: 799 },
      { name: "Earpiece Speaker & Mic", price: 349 },
      { name: "Back Cover / Frame Replacement", price: 499 },
    ],
  },
  {
    id: "brand_oneplus",
    name: "OnePlus",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/OP_LU_Reg_1_Line_POS_RGB.svg/500px-OP_LU_Reg_1_Line_POS_RGB.svg.png",
    models: ["OnePlus 12", "OnePlus 12R", "OnePlus 11", "OnePlus Nord CE 4", "OnePlus 10T"],
    repairs: [
      { name: "Fluid AMOLED Display (No Green Line)", price: 2799 },
      { name: "Warp / SUPERVOOC Battery", price: 1099 },
      { name: "Alert Slider & Volume Button Fix", price: 399 },
      { name: "Motherboard Thermal Pasting & IC", price: 899 },
    ],
  },
  {
    id: "brand_realme",
    name: "Realme",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Realme_logo.svg/500px-Realme_logo.svg.png",
    models: ["Realme 12 Pro+ 5G", "Realme GT 6", "Realme Narzo 70 Pro", "Realme 11", "Realme C67"],
    repairs: [
      { name: "Curved Vision Display Replacement", price: 1699 },
      { name: "DART / SuperVOOC Port Replacement", price: 449 },
      { name: "Massive 5000mAh Battery Fix", price: 799 },
      { name: "Periscope Camera Lens Glass", price: 499 },
    ],
  },
  {
    id: "brand_vivo",
    name: "Vivo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Vivo_mobile_logo.png/500px-Vivo_mobile_logo.png",
    models: ["Vivo V30 Pro", "Vivo X100", "Vivo T3 5G", "Vivo Y200", "Vivo V29"],
    repairs: [
      { name: "3D Curved AMOLED Screen", price: 1999 },
      { name: "ZEISS Camera Sensor Module", price: 1299 },
      { name: "Battery & FlashCharge Motherboard", price: 849 },
      { name: "Aura Ring Light & Flash Repair", price: 399 },
    ],
  },
  {
    id: "brand_oppo",
    name: "OPPO",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/OPPO_Logo.svg/500px-OPPO_Logo.svg.png",
    models: ["OPPO Reno 11 Pro", "OPPO Find X7", "OPPO F25 Pro", "OPPO A79 5G", "OPPO K12x"],
    repairs: [
      { name: "OLED Borderless Display", price: 1899 },
      { name: "SUPERVOOC 80W Charging Port", price: 499 },
      { name: "Battery Replacement (High Durability)", price: 899 },
      { name: "Water Ingress & Diagnostic Clean", price: 549 },
    ],
  },
  {
    id: "brand_poco",
    name: "POCO",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/POCO_Smartphone_logo.png/500px-POCO_Smartphone_logo.png",
    models: ["POCO X6 Pro 5G", "POCO F5 5G", "POCO M6 Pro", "POCO X5", "POCO C65"],
    repairs: [
      { name: "1.5K Flow AMOLED Display", price: 1699 },
      { name: "Gaming Motherboard Reballing & CPU", price: 1299 },
      { name: "Battery & Turbo Charging Board", price: 799 },
      { name: "Dual Stereo Speaker Repair", price: 399 },
    ],
  },
  {
    id: "brand_moto",
    name: "Motorola",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Motorola_new_logo.svg/500px-Motorola_new_logo.svg.png",
    models: ["Moto Edge 50 Pro", "Moto G84 5G", "Moto G64", "Razr 50 Ultra", "Moto Edge 40 Neo"],
    repairs: [
      { name: "pOLED 144Hz Panton Display", price: 2199 },
      { name: "TurboPower Charging & Port", price: 499 },
      { name: "Waterproof Seal & Battery Replacement", price: 899 },
      { name: "Wireless Charging Coil Fix", price: 599 },
    ],
  },
  {
    id: "brand_pixel",
    name: "Google Pixel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/500px-Google_2015_logo.svg.png",
    models: ["Pixel 9 Pro", "Pixel 8a", "Pixel 8 Pro", "Pixel 7a", "Pixel 7", "Pixel 6a"],
    repairs: [
      { name: "Google Actua OLED Screen", price: 3299 },
      { name: "Google Tensor Battery & Thermal Pack", price: 1499 },
      { name: "Camera Bar Glass Replacement", price: 799 },
      { name: "Fingerprint Sensor Re-calibration", price: 499 },
    ],
  },
];

export const MOCK_PRODUCTS: import("../types").Product[] = [
  // 📱 Mobile Phones & Devices
  {
    id: "prod_mob_1",
    name: "Apple iPhone 15 (128GB - Blue)",
    category: "MOBILE_PHONES",
    categoryName: "Mobile Phones",
    description: "Dynamic Island, 48MP Main Camera, A16 Bionic Chip, USB-C Charging with 1 Year Apple Warranty.",
    price: 65999,
    originalPrice: 79900,
    discountPercentage: 17,
    unit: "1 Unit",
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 30,
    brand: "Apple",
  },
  {
    id: "prod_mob_2",
    name: "Samsung Galaxy S24 5G (8GB / 256GB)",
    category: "MOBILE_PHONES",
    categoryName: "Mobile Phones",
    description: "Galaxy AI, Circle to Search, 50MP Pro-visual Engine, Armor Aluminum with Gorilla Armor.",
    price: 74999,
    originalPrice: 84999,
    discountPercentage: 12,
    unit: "1 Unit",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 30,
    brand: "Samsung",
  },
  {
    id: "prod_mob_3",
    name: "OnePlus 12R 5G (16GB RAM / 256GB)",
    category: "MOBILE_PHONES",
    categoryName: "Mobile Phones",
    description: "Snapdragon 8 Gen 2, 4th Gen LTPO 120Hz ProXDR Display, 5500mAh Battery with 100W SUPERVOOC.",
    price: 42999,
    originalPrice: 45999,
    discountPercentage: 7,
    unit: "1 Unit",
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 30,
    brand: "OnePlus",
  },
  {
    id: "prod_mob_4",
    name: "Redmi Note 13 Pro 5G (8GB / 128GB)",
    category: "MOBILE_PHONES",
    categoryName: "Mobile Phones",
    description: "200MP OIS Camera, 1.5K 120Hz Curved AMOLED, 67W Turbo Charge with 1 Year Warranty.",
    price: 18999,
    originalPrice: 23999,
    discountPercentage: 21,
    unit: "1 Unit",
    imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=500&q=80",
    inStock: true,
    rating: 4.7,
    deliveryTimeMins: 30,
    brand: "Xiaomi / Redmi",
  },
  {
    id: "prod_mob_5",
    name: "Realme 12 Pro+ 5G (Submarine Blue)",
    category: "MOBILE_PHONES",
    categoryName: "Mobile Phones",
    description: "64MP Periscope Portrait Camera, Luxury Watch Design, 120Hz Curved Display, 67W SUPERVOOC.",
    price: 29999,
    originalPrice: 34999,
    discountPercentage: 14,
    unit: "1 Unit",
    imageUrl: "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 30,
    brand: "Realme",
  },

  // 🔌 Mobile Accessories & Peripherals
  {
    id: "prod_acc_1",
    name: "65W SuperVOOC / Dash Fast Charger with Type-C Cable",
    category: "MOBILE_ACCESSORIES",
    categoryName: "Mobile Accessories",
    description: "Ultra-fast charging for OnePlus, Realme, Oppo, Samsung, Xiaomi with multi-layer surge protection.",
    price: 699,
    originalPrice: 1499,
    discountPercentage: 53,
    unit: "1 Pack",
    imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 15,
  },
  {
    id: "prod_acc_2",
    name: "9D Edge-to-Edge Tempered Glass (All Models)",
    category: "MOBILE_ACCESSORIES",
    categoryName: "Mobile Accessories",
    description: "Oleophobic coating, anti-fingerprint, scratch resistant, high touch sensitivity.",
    price: 199,
    originalPrice: 499,
    discountPercentage: 60,
    unit: "1 Piece",
    imageUrl: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=500&q=80",
    inStock: true,
    rating: 4.7,
    deliveryTimeMins: 15,
  },
  {
    id: "prod_acc_3",
    name: "Shockproof Airbag Silicon Back Cover (Clear Anti-Yellow)",
    category: "MOBILE_ACCESSORIES",
    categoryName: "Mobile Accessories",
    description: "Military grade drop protection with raised camera bumper and crystal transparency.",
    price: 149,
    originalPrice: 399,
    discountPercentage: 63,
    unit: "1 Piece",
    imageUrl: "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 15,
  },
  {
    id: "prod_acc_4",
    name: "Braided Nylon 100W Fast Type-C to Type-C Cable (1.5m)",
    category: "MOBILE_ACCESSORIES",
    categoryName: "Mobile Accessories",
    description: "Heavy duty zinc alloy connectors, 480Mbps data transfer speed, 10,000+ bend lifespan.",
    price: 249,
    originalPrice: 599,
    discountPercentage: 58,
    unit: "1 Piece",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 15,
  },
  {
    id: "prod_acc_5",
    name: "Magnetic 360° Rotating Car Dashboard Phone Mount",
    category: "MOBILE_ACCESSORIES",
    categoryName: "Mobile Accessories",
    description: "6x N52 Neodymium magnets for bumpy roads, strong 3M adhesive base, universal fit.",
    price: 349,
    originalPrice: 799,
    discountPercentage: 56,
    unit: "1 Piece",
    imageUrl: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=500&q=80",
    inStock: true,
    rating: 4.7,
    deliveryTimeMins: 15,
  },

  // 🛒 Grocery & Instant Blinkit-Style Essentials
  {
    id: "prod_groc_1",
    name: "Fortune Premium Kachi Ghani Pure Mustard Oil (1L)",
    category: "GROCERY",
    categoryName: "Grocery & Staples",
    description: "Cold pressed rich aroma authentic mustard oil for healthy everyday Indian cooking.",
    price: 145,
    originalPrice: 175,
    discountPercentage: 17,
    unit: "1 Litre Pouch",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_2",
    name: "Aashirvaad Shudh Chakki Fresh Atta (10kg)",
    category: "GROCERY",
    categoryName: "Grocery & Staples",
    description: "100% whole wheat grain flour, high dietary fiber for ultra soft rotis.",
    price: 435,
    originalPrice: 490,
    discountPercentage: 11,
    unit: "10 kg Bag",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 15,
  },
  {
    id: "prod_groc_3",
    name: "India Gate Super Basmati Rice (5kg)",
    category: "GROCERY",
    categoryName: "Grocery & Staples",
    description: "Aged long grain aromatic basmati rice for royal biryani, pulao and daily meals.",
    price: 520,
    originalPrice: 650,
    discountPercentage: 20,
    unit: "5 kg Bag",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 15,
  },
  {
    id: "prod_groc_4",
    name: "Amul Pasteurised Pure Salted Butter (500g)",
    category: "GROCERY",
    categoryName: "Dairy & Breakfast",
    description: "The classic Utterly Butterly Delicious taste of pure cow & buffalo milk butter.",
    price: 275,
    originalPrice: 295,
    discountPercentage: 7,
    unit: "500g Block",
    imageUrl: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_5",
    name: "Amul Taaza Homogenised Toned Milk (1 Litre Tetra Pack)",
    category: "GROCERY",
    categoryName: "Dairy & Breakfast",
    description: "Fresh toned milk, rich in calcium and protein, zero preservatives.",
    price: 72,
    originalPrice: 76,
    discountPercentage: 5,
    unit: "1 Litre",
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_6",
    name: "Maggi 2-Minute Masala Instant Noodles (Pack of 12)",
    category: "GROCERY",
    categoryName: "Snacks & Instant Food",
    description: "India's favorite noodle with goodness of iron and signature aromatic spice mix.",
    price: 168,
    originalPrice: 192,
    discountPercentage: 12,
    unit: "840g (12 x 70g)",
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_7",
    name: "Tata Salt Vacuum Evaporated Iodised Salt (1kg)",
    category: "GROCERY",
    categoryName: "Grocery & Staples",
    description: "Desh ka Namak, purified with vacuum evaporation for optimal mental development.",
    price: 28,
    originalPrice: 30,
    discountPercentage: 7,
    unit: "1 kg Pouch",
    imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_8",
    name: "Brooke Bond Red Label Strong CTC Tea (500g)",
    category: "GROCERY",
    categoryName: "Beverages",
    description: "Swad Apnepann Ka - Crafted tea blend with vibrant red colour and strong aroma.",
    price: 240,
    originalPrice: 285,
    discountPercentage: 16,
    unit: "500g Pack",
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_9",
    name: "Fresh Farm Red Onions (2kg Mesh Bag)",
    category: "FRESH_VEGGIES_FRUITS",
    categoryName: "Fresh Veggies & Fruits",
    description: "Directly sourced crisp onions, dry skin, rich pungent flavor for gravies.",
    price: 68,
    originalPrice: 90,
    discountPercentage: 24,
    unit: "2 kg",
    imageUrl: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=500&q=80",
    inStock: true,
    rating: 4.7,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_10",
    name: "Fresh Hybrid Potatoes (2kg)",
    category: "FRESH_VEGGIES_FRUITS",
    categoryName: "Fresh Veggies & Fruits",
    description: "Selected smooth thin-skinned potatoes, perfect for curries, boiling and frying.",
    price: 54,
    originalPrice: 70,
    discountPercentage: 23,
    unit: "2 kg",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_11",
    name: "Coca-Cola Original Taste Chilled Soft Drink (750ml)",
    category: "SNACKS_BEVERAGES",
    categoryName: "Snacks & Drinks",
    description: "Refreshing fizzy carbonated beverage served super chilled at your doorstep.",
    price: 40,
    originalPrice: 40,
    discountPercentage: 0,
    unit: "750 ml Bottle",
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 10,
  },
  {
    id: "prod_groc_12",
    name: "Lay's Spanish Tomato Tango Potato Chips (73g)",
    category: "SNACKS_BEVERAGES",
    categoryName: "Snacks & Drinks",
    description: "Crispy crinkle-cut potato chips spiced with tangy sun-ripened Spanish tomatoes.",
    price: 30,
    originalPrice: 30,
    discountPercentage: 0,
    unit: "73g Pouch",
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 10,
  },

  // 💄 Beauty & Parlour / Salon Products & Doorstep Kits
  {
    id: "prod_beauty_1",
    name: "VLCC Natural Gold Radiance Salon Facial Kit (60g)",
    category: "BEAUTY_PARLOUR",
    categoryName: "Beauty & Parlour",
    description: "Infused with 24K pure gold bhasma and rose petal extracts for bridal radiant glow.",
    price: 299,
    originalPrice: 375,
    discountPercentage: 20,
    unit: "Single Use Kit",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 20,
  },
  {
    id: "prod_beauty_2",
    name: "L'Oreal Paris Professional Hair Spa Creambath (490g)",
    category: "BEAUTY_PARLOUR",
    categoryName: "Beauty & Parlour",
    description: "Deep nourishing water-lily formula for damaged, dry and chemically treated hair.",
    price: 649,
    originalPrice: 799,
    discountPercentage: 19,
    unit: "490g Jar",
    imageUrl: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 20,
  },
  {
    id: "prod_beauty_3",
    name: "Maybelline New York Super Stay Matte Ink Liquid Lipstick",
    category: "BEAUTY_PARLOUR",
    categoryName: "Beauty & Parlour",
    description: "16-Hour long wear transfer-proof saturated matte liquid color (Shade: 80 Ruler).",
    price: 549,
    originalPrice: 699,
    discountPercentage: 21,
    unit: "5 ml",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 20,
  },
  {
    id: "prod_beauty_4",
    name: "Nivea Soft Light Moisturiser with Vitamin E & Jojoba Oil (300ml)",
    category: "BEAUTY_PARLOUR",
    categoryName: "Beauty & Parlour",
    description: "Non-greasy quick absorbing daily hydration cream for face, body and hands.",
    price: 360,
    originalPrice: 450,
    discountPercentage: 20,
    unit: "300 ml Tub",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 20,
  },
  {
    id: "prod_beauty_5",
    name: "Philips 1000W Compact Foldable Hair Dryer",
    category: "BEAUTY_PARLOUR",
    categoryName: "Beauty & Parlour",
    description: "ThermoProtect temperature setting, 2 flexible speed settings with narrow concentrator.",
    price: 899,
    originalPrice: 1095,
    discountPercentage: 18,
    unit: "1 Unit",
    imageUrl: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500&q=80",
    inStock: true,
    rating: 4.7,
    deliveryTimeMins: 25,
  },

  // 🏠 Home, Hygiene & Daily Needs
  {
    id: "prod_home_1",
    name: "Surf Excel Matic Front & Top Load Detergent Powder (2kg)",
    category: "HOME_NEEDS",
    categoryName: "Home Needs",
    description: "Tough stain removal with fresh floral fragrance in washing machines.",
    price: 360,
    originalPrice: 420,
    discountPercentage: 14,
    unit: "2 kg Pack",
    imageUrl: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 20,
  },
  {
    id: "prod_home_2",
    name: "Lizol Disinfectant Surface Cleaner Citrus (2L)",
    category: "HOME_NEEDS",
    categoryName: "Home Needs",
    description: "Kills 99.9% germs, removes tough grease and leaves long-lasting citrus fragrance.",
    price: 340,
    originalPrice: 399,
    discountPercentage: 15,
    unit: "2 Litres",
    imageUrl: "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 20,
  },
  {
    id: "prod_home_3",
    name: "Dettol Liquid Handwash Refill Pouch (1500ml)",
    category: "HOME_NEEDS",
    categoryName: "Home Needs",
    description: "Original pine fragrance with 10x better germ protection and natural moisturizers.",
    price: 199,
    originalPrice: 249,
    discountPercentage: 20,
    unit: "1.5 Litre Refill",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 15,
  },
  {
    id: "prod_home_4",
    name: "Harpic Power Plus Disinfectant Toilet Cleaner (1L x 2 Twin Pack)",
    category: "HOME_NEEDS",
    categoryName: "Home Needs",
    description: "10x max power removes limescale, yellow stains and kills 99.9% germs.",
    price: 320,
    originalPrice: 380,
    discountPercentage: 16,
    unit: "2 x 1 Litre",
    imageUrl: "https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=500&q=80",
    inStock: true,
    rating: 4.8,
    deliveryTimeMins: 15,
  },

  // 🎧 Electronics & Audio
  {
    id: "prod_elec_1",
    name: "boAt Airdopes 141 Bluetooth TWS Earbuds",
    category: "ELECTRONICS",
    categoryName: "Electronics",
    description: "42H Playtime, ENx Tech, Beast Mode 80ms Low Latency, IPX4 Water Resistance.",
    price: 999,
    originalPrice: 2990,
    discountPercentage: 66,
    unit: "1 Unit",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&q=80",
    inStock: true,
    rating: 4.7,
    deliveryTimeMins: 25,
  },
  {
    id: "prod_elec_2",
    name: "Mi 20000mAh 18W Fast Charging Power Bank 3i",
    category: "ELECTRONICS",
    categoryName: "Electronics",
    description: "Triple port output, Dual input (Micro-USB & Type-C) with 12 layer circuit protection.",
    price: 1899,
    originalPrice: 2499,
    discountPercentage: 24,
    unit: "1 Unit",
    imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500&q=80",
    inStock: true,
    rating: 4.9,
    deliveryTimeMins: 25,
  },
];

export const MOCK_COUPONS: import("../types").Coupon[] = [
  {
    code: "INISHA50",
    discountType: "PERCENTAGE",
    discountValue: 20,
    minOrderValue: 299,
    maxDiscount: 150,
    description: "Get 20% OFF up to ₹150 on all doorstep services",
    expiresAt: "2026-12-31",
  },
  {
    code: "FIRST100",
    discountType: "FLAT",
    discountValue: 100,
    minOrderValue: 499,
    description: "Flat ₹100 OFF on your first booking or order",
    expiresAt: "2026-12-31",
  },
  {
    code: "SUPER20",
    discountType: "PERCENTAGE",
    discountValue: 10,
    minOrderValue: 199,
    maxDiscount: 100,
    description: "10% instant discount on grocery & accessories",
    expiresAt: "2026-12-31",
  },
];

export const MOCK_CITIES: import("../types").FranchiseCity[] = [
  {
    id: "city_patna",
    cityName: "Patna",
    state: "Bihar",
    isActive: true,
    managerName: "Rajesh Kumar",
    managerPhone: "+91 98350 12345",
    totalProviders: 142,
    monthlyGmv: 1250000,
  },
  {
    id: "city_muzaffarpur",
    cityName: "Muzaffarpur",
    state: "Bihar",
    isActive: true,
    managerName: "Amitabh Sinha",
    managerPhone: "+91 94312 67890",
    totalProviders: 68,
    monthlyGmv: 540000,
  },
  {
    id: "city_gaya",
    cityName: "Gaya",
    state: "Bihar",
    isActive: true,
    managerName: "Sunil Verma",
    managerPhone: "+91 91234 56789",
    totalProviders: 45,
    monthlyGmv: 390000,
  },
  {
    id: "city_bhagalpur",
    cityName: "Bhagalpur",
    state: "Bihar",
    isActive: true,
    managerName: "Vikram Mishra",
    managerPhone: "+91 93345 11223",
    totalProviders: 38,
    monthlyGmv: 310000,
  },
  {
    id: "city_delhi",
    cityName: "Delhi NCR",
    state: "Delhi",
    isActive: true,
    managerName: "Pooja Sharma",
    managerPhone: "+91 98110 55667",
    totalProviders: 210,
    monthlyGmv: 2800000,
  },
];

