import { Category } from "../types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat_mobile",
    name: "Mobile Repair",
    slug: "mobile-repair",
    description: "Doorstep screen replacement, battery, charging port, and hardware repair within 60 mins.",
    imageUrl: "phone",
    isActive: true,
    subcategories: [
      {
        id: "sub_mob_doorstep",
        categoryId: "cat_mobile",
        name: "Doorstep Mobile Screen & Hardware Repair",
        slug: "doorstep-mobile-repair",
        description: "Certified technicians fix your phone right in front of you at your home or office.",
        basePrice: 499,
        imageUrl: "smartphone",
        formConfig: {
          fields: [
            {
              id: "device_model",
              label: "Mobile Brand & Model",
              type: "TEXT",
              placeholder: "e.g., iPhone 13, OnePlus 11, Samsung S23, Redmi Note 12",
              validation: { required: true, min: 2 },
            },
            {
              id: "repair_type",
              label: "Required Repair Service",
              type: "SELECT",
              options: [
                { label: "Original Screen Replacement", value: "screen", priceModifier: 1499 },
                { label: "Battery Replacement (100% Health)", value: "battery", priceModifier: 799 },
                { label: "Charging Port / Mic Replacement", value: "charging", priceModifier: 399 },
                { label: "Back Glass / Camera Glass Fix", value: "camera_glass", priceModifier: 499 },
                { label: "Water Damage / Motherboard Diagnosis", value: "motherboard", priceModifier: 599 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Preferred Visit Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Preferred Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Doorstep Service Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_ac_repair",
    name: "AC Repair & Service",
    slug: "ac-repair",
    description: "Deep jet foam cleaning, gas refill, installation, cooling issues & PCB breakdown repairs.",
    imageUrl: "wind",
    isActive: true,
    subcategories: [
      {
        id: "sub_ac_service",
        categoryId: "cat_ac_repair",
        name: "Split & Window AC Complete Service",
        slug: "split-window-ac-service",
        description: "Power jet deep cleaning with foam spray, coil check & cooling optimization.",
        basePrice: 399,
        imageUrl: "wind",
        formConfig: {
          fields: [
            {
              id: "ac_type",
              label: "AC Type & Ton",
              type: "SELECT",
              options: [
                { label: "Split AC (1 - 1.5 Ton)", value: "split_1.5", priceModifier: 100 },
                { label: "Split AC (2 Ton)", value: "split_2", priceModifier: 200 },
                { label: "Window AC (All Sizes)", value: "window", priceModifier: 0 },
                { label: "Cassette / Tower Commercial AC", value: "cassette", priceModifier: 600 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "service_required",
              label: "Service Needed",
              type: "SELECT",
              options: [
                { label: "Power Jet Deep Cleaning & Foam Wash", value: "jet_service", priceModifier: 250 },
                { label: "Gas Leakage Detection & Full Gas Refill", value: "gas_refill", priceModifier: 1400 },
                { label: "AC Not Cooling / Water Dripping Issue", value: "not_cooling", priceModifier: 199 },
                { label: "New AC Installation / Uninstallation", value: "installation", priceModifier: 800 },
                { label: "PCB / Inverter Motherboard Repair", value: "pcb_repair", priceModifier: 950 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Service Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Service Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_electrician",
    name: "Electrician",
    slug: "electrician",
    description: "Certified electricians for fan, switchboard, MCB wiring, lights & short-circuit breakdown.",
    imageUrl: "zap",
    isActive: true,
    subcategories: [
      {
        id: "sub_electrician_general",
        categoryId: "cat_electrician",
        name: "Electrician Doorstep Visit & Repair",
        slug: "electrician-visit",
        description: "Instant doorstep assistance for domestic & commercial electrical faults.",
        basePrice: 199,
        imageUrl: "zap",
        formConfig: {
          fields: [
            {
              id: "electrical_job",
              label: "Choose Electrical Work",
              type: "SELECT",
              options: [
                { label: "Fan Repair / Installation / Regulators", value: "fan", priceModifier: 150 },
                { label: "Switchboard / Socket / Fuse Replacement", value: "switchboard", priceModifier: 100 },
                { label: "MCB Tripping / Short Circuit Fault Finding", value: "mcb_fault", priceModifier: 350 },
                { label: "Inverter & Battery Wiring Setup", value: "inverter", priceModifier: 400 },
                { label: "Decorative Chandelier & LED Strip Lighting", value: "led_lights", priceModifier: 300 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Preferred Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Preferred Time",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Home Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_plumber",
    name: "Plumber",
    slug: "plumber",
    description: "Expert plumbers for tap repair, pipe leakages, water tank cleaning, shower & toilet fittings.",
    imageUrl: "droplets",
    isActive: true,
    subcategories: [
      {
        id: "sub_plumber_visit",
        categoryId: "cat_plumber",
        name: "Plumbing Inspection & Repair",
        slug: "plumbing-repair",
        description: "Quick doorstep solution for blocked drains, tap leaks & sanitary installations.",
        basePrice: 199,
        imageUrl: "droplets",
        formConfig: {
          fields: [
            {
              id: "plumbing_issue",
              label: "Select Plumbing Requirement",
              type: "SELECT",
              options: [
                { label: "Tap / Mixer / Shower Leakage Repair", value: "tap_leak", priceModifier: 100 },
                { label: "Drain Blockage / Clogged Basin Cleaning", value: "blockage", priceModifier: 250 },
                { label: "Water Tank Deep Cleaning (500L - 1000L)", value: "tank_clean", priceModifier: 600 },
                { label: "Toilet Seat / Flush Tank Replacement", value: "toilet_fit", priceModifier: 450 },
                { label: "Main Water Motor / Pump Pipe Fitting", value: "motor_pipe", priceModifier: 350 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_carpenter",
    name: "Carpenter",
    slug: "carpenter",
    description: "Furniture repair, bed assembly, modular kitchen fittings, door locks, hinges & wood polish.",
    imageUrl: "hammer",
    isActive: true,
    subcategories: [
      {
        id: "sub_carpenter_visit",
        categoryId: "cat_carpenter",
        name: "Carpentry & Furniture Works",
        slug: "carpentry-works",
        description: "Skilled carpenters for quick repairs, new fittings and custom woodwork.",
        basePrice: 299,
        imageUrl: "hammer",
        formConfig: {
          fields: [
            {
              id: "carpenter_work",
              label: "Carpentry Requirement",
              type: "SELECT",
              options: [
                { label: "Door Lock / Latch / Handle Fitting", value: "lock_fitting", priceModifier: 150 },
                { label: "Bed / Wardrobe Assembly & Disassembly", value: "bed_assembly", priceModifier: 500 },
                { label: "Cabinet / Drawer Hinge & Channel Repair", value: "hinge_fix", priceModifier: 200 },
                { label: "Wooden Partition / Shelves Installation", value: "shelves", priceModifier: 400 },
                { label: "Wood Polishing & Touch-up (Small / Large)", value: "polishing", priceModifier: 650 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_cleaning",
    name: "Home Cleaning",
    slug: "home-cleaning",
    description: "Full home deep cleaning, kitchen & bathroom sanitation, sofa, carpet & mattress shampoo.",
    imageUrl: "sparkles",
    isActive: true,
    subcategories: [
      {
        id: "sub_home_deep_clean",
        categoryId: "cat_cleaning",
        name: "Deep Home Cleaning & Sanitation",
        slug: "deep-home-cleaning",
        description: "Eco-friendly chemicals, motorized floor scrubbers and trained cleaners.",
        basePrice: 599,
        imageUrl: "sparkles",
        formConfig: {
          fields: [
            {
              id: "cleaning_package",
              label: "Choose Cleaning Package",
              type: "SELECT",
              options: [
                { label: "Bathroom Deep Cleaning (Per Bathroom)", value: "bathroom", priceModifier: 299 },
                { label: "Kitchen Deep Degreasing & Cabinet Clean", value: "kitchen", priceModifier: 699 },
                { label: "1 BHK Full Home Deep Cleaning", value: "1bhk", priceModifier: 1499 },
                { label: "2 BHK Full Home Deep Cleaning", value: "2bhk", priceModifier: 2199 },
                { label: "3 BHK Full Home Deep Cleaning", value: "3bhk", priceModifier: 2899 },
                { label: "Sofa / Carpet Dry Cleaning & Shampoo", value: "sofa_clean", priceModifier: 550 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_salon",
    name: "Home Salon",
    slug: "home-salon",
    description: "Hygienic salon at home for women & men: facials, waxing, manicure, pedicure & hair styling.",
    imageUrl: "scissors",
    isActive: true,
    subcategories: [
      {
        id: "sub_salon_package",
        categoryId: "cat_salon",
        name: "Beauty, Hair & Spa Treatments",
        slug: "beauty-spa-home",
        description: "100% single-use disposable kits and branded premium beauty products.",
        basePrice: 499,
        imageUrl: "scissors",
        formConfig: {
          fields: [
            {
              id: "salon_package",
              label: "Select Salon Services",
              type: "MULTI_SELECT",
              options: [
                { label: "Diamond Glowing Facial & Clean-up", value: "facial", priceModifier: 699 },
                { label: "Honey Full Arms & Legs Waxing", value: "waxing", priceModifier: 499 },
                { label: "Rose Petal Deluxe Pedicure & Manicure", value: "pedi_mani", priceModifier: 599 },
                { label: "Hair Spa + Head Massage + Blow Dry", value: "hair_spa", priceModifier: 799 },
                { label: "Men Haircut & Beard Styling + De-tan", value: "men_grooming", priceModifier: 399 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_appliance",
    name: "Appliance Repair",
    slug: "appliance-repair",
    description: "Doorstep service for Microwave Oven, Geyser, Water Heater, Mixer & Kitchen Chimney.",
    imageUrl: "wrench",
    isActive: true,
    subcategories: [
      {
        id: "sub_small_appliance",
        categoryId: "cat_appliance",
        name: "Small & Kitchen Appliance Repair",
        slug: "small-appliance-repair",
        description: "Fast doorstep troubleshooting for all electrical appliances with genuine spares.",
        basePrice: 299,
        imageUrl: "wrench",
        formConfig: {
          fields: [
            {
              id: "appliance_type",
              label: "Appliance to Repair",
              type: "SELECT",
              options: [
                { label: "Geyser / Water Heater Not Heating / Leaking", value: "geyser", priceModifier: 150 },
                { label: "Microwave Oven / OTG Not Heating / Sparking", value: "microwave", priceModifier: 200 },
                { label: "Kitchen Chimney Deep Cleaning & Motor Fix", value: "chimney", priceModifier: 450 },
                { label: "Mixer / Grinder / Juicer Blade & Motor", value: "mixer", priceModifier: 100 },
                { label: "Induction Cooktop / Electric Kettle", value: "induction", priceModifier: 150 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_painting",
    name: "Painting",
    slug: "painting",
    description: "Interior & exterior wall painting, waterproof damp treatment, texture paint and stencil designs.",
    imageUrl: "paint-brush",
    isActive: true,
    subcategories: [
      {
        id: "sub_painting_services",
        categoryId: "cat_painting",
        name: "House & Wall Painting Services",
        slug: "home-painting",
        description: "Laser measurement, wall putty, primer & premium Asian/Berger paint coating.",
        basePrice: 999,
        imageUrl: "paint-brush",
        formConfig: {
          fields: [
            {
              id: "painting_scope",
              label: "Painting Scope",
              type: "SELECT",
              options: [
                { label: "Single Room / Accent Wall Makeover", value: "single_room", priceModifier: 800 },
                { label: "Complete 1/2/3 BHK Interior Painting", value: "full_interior", priceModifier: 3500 },
                { label: "Waterproofing & Damp Wall Treatment", value: "waterproofing", priceModifier: 1200 },
                { label: "Wall Texture & Designer Stencils", value: "texture", priceModifier: 950 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Inspection Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_cctv",
    name: "CCTV Installation",
    slug: "cctv-installation",
    description: "IP & HD CCTV security camera installation, DVR/NVR setup, mobile view and cable routing.",
    imageUrl: "camera",
    isActive: true,
    subcategories: [
      {
        id: "sub_cctv_setup",
        categoryId: "cat_cctv",
        name: "CCTV Security Camera Setup",
        slug: "cctv-setup",
        description: "Professional camera alignment, smartphone live remote viewing and night vision config.",
        basePrice: 499,
        imageUrl: "camera",
        formConfig: {
          fields: [
            {
              id: "cctv_service",
              label: "CCTV Requirement",
              type: "SELECT",
              options: [
                { label: "New CCTV Camera Installation (Per Camera)", value: "new_install", priceModifier: 250 },
                { label: "Complete 4-Camera Setup with DVR & Hard Disk", value: "4_cam_kit", priceModifier: 1200 },
                { label: "CCTV Mobile App Remote View / Offline Fix", value: "mobile_view", priceModifier: 200 },
                { label: "Camera Relocation / Wire Routing & Repair", value: "relocate", priceModifier: 350 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_ro_service",
    name: "RO Service",
    slug: "ro-service",
    description: "Water purifier RO filter change, membrane replacement, UV lamp fix and TDS calibration.",
    imageUrl: "droplet",
    isActive: true,
    subcategories: [
      {
        id: "sub_ro_filter_change",
        categoryId: "cat_ro_service",
        name: "RO Purifier Maintenance & Repair",
        slug: "ro-purifier-repair",
        description: "Genuine Kent, Aquaguard, Livpure filters with strict water TDS testing.",
        basePrice: 299,
        imageUrl: "droplet",
        formConfig: {
          fields: [
            {
              id: "ro_service_type",
              label: "Select RO Service",
              type: "SELECT",
              options: [
                { label: "General Service & Complete Filter Deep Clean", value: "general_clean", priceModifier: 150 },
                { label: "Sediment + Carbon + Post Carbon Filter Set", value: "filter_set", priceModifier: 650 },
                { label: "RO Membrane Replacement (High TDS Fix)", value: "membrane", priceModifier: 1100 },
                { label: "Water Purifier Booster Pump / SMPS Repair", value: "pump_smps", priceModifier: 750 },
                { label: "New RO Purifier Installation / Uninstallation", value: "ro_install", priceModifier: 350 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_computer",
    name: "Computer/Laptop Repair",
    slug: "computer-laptop-repair",
    description: "Doorstep diagnostic for slow laptops, Windows/Mac OS install, SSD speedup, keyboard & screen.",
    imageUrl: "monitor",
    isActive: true,
    subcategories: [
      {
        id: "sub_computer_repair",
        categoryId: "cat_computer",
        name: "Laptop & PC Doorstep Diagnostic",
        slug: "laptop-pc-repair",
        description: "Hardware & software fixes for Dell, HP, Lenovo, Asus, Acer & Apple MacBook.",
        basePrice: 499,
        imageUrl: "monitor",
        formConfig: {
          fields: [
            {
              id: "laptop_issue",
              label: "Issue / Required Upgrade",
              type: "SELECT",
              options: [
                { label: "High-Speed SSD Upgrade (Make Laptop 10x Faster)", value: "ssd_speedup", priceModifier: 350 },
                { label: "Original Windows 11 / Mac OS Installation", value: "os_install", priceModifier: 300 },
                { label: "Laptop Screen / Display Replacement", value: "screen_replace", priceModifier: 1800 },
                { label: "Laptop Battery / Charger / Power Jack Repair", value: "battery_power", priceModifier: 450 },
                { label: "Motherboard Chip-Level Repair / Dead Laptop", value: "motherboard", priceModifier: 950 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_washing_machine",
    name: "Washing Machine Repair",
    slug: "washing-machine-repair",
    description: "Front load & top load washing machine repair: water leakage, drum noise, vibration & PCB.",
    imageUrl: "disc",
    isActive: true,
    subcategories: [
      {
        id: "sub_washing_machine_fix",
        categoryId: "cat_washing_machine",
        name: "Automatic & Semi-Automatic Machine Repair",
        slug: "washing-machine-repair-service",
        description: "Certified technicians for LG, Samsung, Whirlpool, IFB, Bosch & Haier.",
        basePrice: 349,
        imageUrl: "disc",
        formConfig: {
          fields: [
            {
              id: "machine_type",
              label: "Machine Type",
              type: "SELECT",
              options: [
                { label: "Fully Automatic Front Load", value: "front_load", priceModifier: 150 },
                { label: "Fully Automatic Top Load", value: "top_load", priceModifier: 100 },
                { label: "Semi-Automatic (Twin Tub)", value: "semi_auto", priceModifier: 0 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "machine_problem",
              label: "Primary Problem",
              type: "SELECT",
              options: [
                { label: "Machine Not Spinning / Drum Not Moving", value: "not_spinning", priceModifier: 200 },
                { label: "Water Not Draining / Continuous Water Intake", value: "water_issue", priceModifier: 150 },
                { label: "Excessive Vibration & Noise during Spin", value: "noise_vibration", priceModifier: 300 },
                { label: "Machine Dead / PCB Display Error Codes", value: "pcb_error", priceModifier: 600 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_refrigerator",
    name: "Refrigerator Repair",
    slug: "refrigerator-repair",
    description: "Doorstep fridge repair: single & double door, cooling fault, compressor, gas charge & thermostat.",
    imageUrl: "snowflake",
    isActive: true,
    subcategories: [
      {
        id: "sub_fridge_repair",
        categoryId: "cat_refrigerator",
        name: "Refrigerator Cooling & Gas Service",
        slug: "fridge-service",
        description: "Same-day doorstep inspection for Samsung, LG, Whirlpool, Godrej & Haier.",
        basePrice: 349,
        imageUrl: "snowflake",
        formConfig: {
          fields: [
            {
              id: "fridge_type",
              label: "Refrigerator Type",
              type: "SELECT",
              options: [
                { label: "Single Door Refrigerator", value: "single_door", priceModifier: 0 },
                { label: "Double Door Frost-Free Refrigerator", value: "double_door", priceModifier: 150 },
                { label: "Side-by-Side / French Door Fridge", value: "side_by_side", priceModifier: 400 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "fridge_issue",
              label: "Issue Observed",
              type: "SELECT",
              options: [
                { label: "Fridge Not Cooling / Low Cooling", value: "not_cooling", priceModifier: 200 },
                { label: "Compressor Gas Charging & Leakage Repair", value: "gas_charge", priceModifier: 1250 },
                { label: "Water Leakage Inside / Ice Sheet Formation", value: "leakage_ice", priceModifier: 250 },
                { label: "Thermostat / Relay / Fan Motor Replacement", value: "thermostat", priceModifier: 450 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
  {
    id: "cat_pest_control",
    name: "Pest Control",
    slug: "pest-control",
    description: "Safe & herbal pest control for cockroaches, termites, bed bugs, ants and mosquitoes.",
    imageUrl: "bug",
    isActive: true,
    subcategories: [
      {
        id: "sub_pest_control_service",
        categoryId: "cat_pest_control",
        name: "Herbal & Odorless Pest Control",
        slug: "home-pest-control",
        description: "100% kid & pet-safe odorless gel and spray with warranty guarantee.",
        basePrice: 699,
        imageUrl: "bug",
        formConfig: {
          fields: [
            {
              id: "pest_type",
              label: "Pest Treatment Type",
              type: "SELECT",
              options: [
                { label: "Cockroach & Ant Herbal Gel (1-3 BHK)", value: "cockroach", priceModifier: 300 },
                { label: "Bed Bugs Complete 2-Visit Treatment", value: "bed_bugs", priceModifier: 900 },
                { label: "Termite (Deemak) Wood & Wall Drilling", value: "termite", priceModifier: 1500 },
                { label: "Mosquito & Flying Insect Fogging", value: "mosquito", priceModifier: 500 },
                { label: "Complete Home 360° All-Pest Protection", value: "all_pest", priceModifier: 1200 },
              ],
              validation: { required: true },
              priceModifierField: true,
            },
            {
              id: "preferred_date",
              label: "Date",
              type: "DATE",
              validation: { required: true },
            },
            {
              id: "preferred_time",
              label: "Time Slot",
              type: "TIME_SLOT",
              validation: { required: true },
            },
            {
              id: "service_address",
              label: "Address",
              type: "ADDRESS_GPS",
              validation: { required: true },
            },
          ],
        },
      },
    ],
  },
];
